const n5Content = {
  levels: [
    { id: "n5", label: "N5", status: "active", description: "Kana, survival phrases, basic particles, and simple sentence patterns." },
    { id: "n4", label: "N4", status: "locked", description: "Daily routines, more verbs, polite requests, and longer listening prompts." },
    { id: "n3", label: "N3", status: "locked", description: "Natural conversation, city-office language, housing, work, and stronger reading." },
    { id: "n2", label: "N2", status: "locked", description: "News, official notices, nuanced grammar, and advanced vocabulary." },
    { id: "n1", label: "N1", status: "locked", description: "High-level reading, formal writing, keigo, essays, and dense listening." }
  ],
  kanaDecks: {
    hiragana: [
      { kana: "あ", romaji: "a", group: "vowels" },
      { kana: "い", romaji: "i", group: "vowels" },
      { kana: "う", romaji: "u", group: "vowels" },
      { kana: "え", romaji: "e", group: "vowels" },
      { kana: "お", romaji: "o", group: "vowels" },
      { kana: "か", romaji: "ka", group: "k" },
      { kana: "き", romaji: "ki", group: "k" },
      { kana: "く", romaji: "ku", group: "k" },
      { kana: "け", romaji: "ke", group: "k" },
      { kana: "こ", romaji: "ko", group: "k" },
      { kana: "さ", romaji: "sa", group: "s" },
      { kana: "し", romaji: "shi", group: "s" },
      { kana: "す", romaji: "su", group: "s" },
      { kana: "せ", romaji: "se", group: "s" },
      { kana: "そ", romaji: "so", group: "s" },
      { kana: "た", romaji: "ta", group: "t" },
      { kana: "ち", romaji: "chi", group: "t" },
      { kana: "つ", romaji: "tsu", group: "t" },
      { kana: "て", romaji: "te", group: "t" },
      { kana: "と", romaji: "to", group: "t" },
      { kana: "な", romaji: "na", group: "n" },
      { kana: "に", romaji: "ni", group: "n" },
      { kana: "ぬ", romaji: "nu", group: "n" },
      { kana: "ね", romaji: "ne", group: "n" },
      { kana: "の", romaji: "no", group: "n" },
      { kana: "は", romaji: "ha", group: "h" },
      { kana: "ひ", romaji: "hi", group: "h" },
      { kana: "ふ", romaji: "fu", group: "h" },
      { kana: "へ", romaji: "he", group: "h" },
      { kana: "ほ", romaji: "ho", group: "h" },
      { kana: "ま", romaji: "ma", group: "m" },
      { kana: "み", romaji: "mi", group: "m" },
      { kana: "む", romaji: "mu", group: "m" },
      { kana: "め", romaji: "me", group: "m" },
      { kana: "も", romaji: "mo", group: "m" },
      { kana: "や", romaji: "ya", group: "y" },
      { kana: "ゆ", romaji: "yu", group: "y" },
      { kana: "よ", romaji: "yo", group: "y" },
      { kana: "ら", romaji: "ra", group: "r" },
      { kana: "り", romaji: "ri", group: "r" },
      { kana: "る", romaji: "ru", group: "r" },
      { kana: "れ", romaji: "re", group: "r" },
      { kana: "ろ", romaji: "ro", group: "r" },
      { kana: "わ", romaji: "wa", group: "w" },
      { kana: "を", romaji: "wo", group: "w" },
      { kana: "ん", romaji: "n", group: "n" }
    ],
    katakana: [
      { kana: "ア", romaji: "a", group: "vowels" },
      { kana: "イ", romaji: "i", group: "vowels" },
      { kana: "ウ", romaji: "u", group: "vowels" },
      { kana: "エ", romaji: "e", group: "vowels" },
      { kana: "オ", romaji: "o", group: "vowels" },
      { kana: "カ", romaji: "ka", group: "k" },
      { kana: "キ", romaji: "ki", group: "k" },
      { kana: "ク", romaji: "ku", group: "k" },
      { kana: "ケ", romaji: "ke", group: "k" },
      { kana: "コ", romaji: "ko", group: "k" },
      { kana: "サ", romaji: "sa", group: "s" },
      { kana: "シ", romaji: "shi", group: "s" },
      { kana: "ス", romaji: "su", group: "s" },
      { kana: "セ", romaji: "se", group: "s" },
      { kana: "ソ", romaji: "so", group: "s" },
      { kana: "タ", romaji: "ta", group: "t" },
      { kana: "チ", romaji: "chi", group: "t" },
      { kana: "ツ", romaji: "tsu", group: "t" },
      { kana: "テ", romaji: "te", group: "t" },
      { kana: "ト", romaji: "to", group: "t" },
      { kana: "ナ", romaji: "na", group: "n" },
      { kana: "ニ", romaji: "ni", group: "n" },
      { kana: "ヌ", romaji: "nu", group: "n" },
      { kana: "ネ", romaji: "ne", group: "n" },
      { kana: "ノ", romaji: "no", group: "n" },
      { kana: "ハ", romaji: "ha", group: "h" },
      { kana: "ヒ", romaji: "hi", group: "h" },
      { kana: "フ", romaji: "fu", group: "h" },
      { kana: "ヘ", romaji: "he", group: "h" },
      { kana: "ホ", romaji: "ho", group: "h" },
      { kana: "マ", romaji: "ma", group: "m" },
      { kana: "ミ", romaji: "mi", group: "m" },
      { kana: "ム", romaji: "mu", group: "m" },
      { kana: "メ", romaji: "me", group: "m" },
      { kana: "モ", romaji: "mo", group: "m" },
      { kana: "ヤ", romaji: "ya", group: "y" },
      { kana: "ユ", romaji: "yu", group: "y" },
      { kana: "ヨ", romaji: "yo", group: "y" },
      { kana: "ラ", romaji: "ra", group: "r" },
      { kana: "リ", romaji: "ri", group: "r" },
      { kana: "ル", romaji: "ru", group: "r" },
      { kana: "レ", romaji: "re", group: "r" },
      { kana: "ロ", romaji: "ro", group: "r" },
      { kana: "ワ", romaji: "wa", group: "w" },
      { kana: "ヲ", romaji: "wo", group: "w" },
      { kana: "ン", romaji: "n", group: "n" }
    ]
  },
  n5Vocabulary: [
    { japanese: "わたし", romaji: "watashi", english: "I / me", category: "people" },
    { japanese: "あなた", romaji: "anata", english: "you", category: "people" },
    { japanese: "ひと", romaji: "hito", english: "person", category: "people" },
    { japanese: "ともだち", romaji: "tomodachi", english: "friend", category: "people" },
    { japanese: "せんせい", romaji: "sensei", english: "teacher", category: "people" },
    { japanese: "がくせい", romaji: "gakusei", english: "student", category: "people" },
    { japanese: "かぞく", romaji: "kazoku", english: "family", category: "people" },
    { japanese: "いえ", romaji: "ie", english: "home / house", category: "daily life" },
    { japanese: "みず", romaji: "mizu", english: "water", category: "daily life" },
    { japanese: "ごはん", romaji: "gohan", english: "rice / meal", category: "daily life" },
    { japanese: "おちゃ", romaji: "ocha", english: "tea", category: "daily life" },
    { japanese: "コーヒー", romaji: "koohii", english: "coffee", category: "daily life" },
    { japanese: "パン", romaji: "pan", english: "bread", category: "daily life" },
    { japanese: "ほん", romaji: "hon", english: "book", category: "daily life" },
    { japanese: "でんわ", romaji: "denwa", english: "telephone", category: "daily life" },
    { japanese: "かばん", romaji: "kaban", english: "bag", category: "daily life" },
    { japanese: "えき", romaji: "eki", english: "station", category: "places" },
    { japanese: "みせ", romaji: "mise", english: "shop", category: "places" },
    { japanese: "がっこう", romaji: "gakkou", english: "school", category: "places" },
    { japanese: "びょういん", romaji: "byouin", english: "hospital", category: "places" },
    { japanese: "ぎんこう", romaji: "ginkou", english: "bank", category: "places" },
    { japanese: "ゆうびんきょく", romaji: "yuubinkyoku", english: "post office", category: "places" },
    { japanese: "トイレ", romaji: "toire", english: "toilet / restroom", category: "places" },
    { japanese: "くるま", romaji: "kuruma", english: "car", category: "transport" },
    { japanese: "でんしゃ", romaji: "densha", english: "train", category: "transport" },
    { japanese: "バス", romaji: "basu", english: "bus", category: "transport" },
    { japanese: "タクシー", romaji: "takushii", english: "taxi", category: "transport" },
    { japanese: "じてんしゃ", romaji: "jitensha", english: "bicycle", category: "transport" },
    { japanese: "いく", romaji: "iku", english: "to go", category: "verbs" },
    { japanese: "くる", romaji: "kuru", english: "to come", category: "verbs" },
    { japanese: "かえる", romaji: "kaeru", english: "to return", category: "verbs" },
    { japanese: "たべる", romaji: "taberu", english: "to eat", category: "verbs" },
    { japanese: "のむ", romaji: "nomu", english: "to drink", category: "verbs" },
    { japanese: "みる", romaji: "miru", english: "to see / watch", category: "verbs" },
    { japanese: "きく", romaji: "kiku", english: "to listen / ask", category: "verbs" },
    { japanese: "はなす", romaji: "hanasu", english: "to speak", category: "verbs" },
    { japanese: "よむ", romaji: "yomu", english: "to read", category: "verbs" },
    { japanese: "かく", romaji: "kaku", english: "to write", category: "verbs" },
    { japanese: "かう", romaji: "kau", english: "to buy", category: "verbs" },
    { japanese: "する", romaji: "suru", english: "to do", category: "verbs" },
    { japanese: "ある", romaji: "aru", english: "to exist / have", category: "verbs" },
    { japanese: "いる", romaji: "iru", english: "to exist / be there (living things)", category: "verbs" },
    { japanese: "いい", romaji: "ii", english: "good", category: "adjectives" },
    { japanese: "おおきい", romaji: "ookii", english: "big", category: "adjectives" },
    { japanese: "ちいさい", romaji: "chiisai", english: "small", category: "adjectives" },
    { japanese: "あたらしい", romaji: "atarashii", english: "new", category: "adjectives" },
    { japanese: "ふるい", romaji: "furui", english: "old (not age)", category: "adjectives" },
    { japanese: "たかい", romaji: "takai", english: "expensive / tall", category: "adjectives" },
    { japanese: "やすい", romaji: "yasui", english: "cheap", category: "adjectives" },
    { japanese: "あつい", romaji: "atsui", english: "hot", category: "adjectives" },
    { japanese: "さむい", romaji: "samui", english: "cold", category: "adjectives" },
    { japanese: "いそがしい", romaji: "isogashii", english: "busy", category: "adjectives" },
    { japanese: "ひま", romaji: "hima", english: "free / not busy", category: "adjectives" },
    { japanese: "きょう", romaji: "kyou", english: "today", category: "time" },
    { japanese: "あした", romaji: "ashita", english: "tomorrow", category: "time" },
    { japanese: "きのう", romaji: "kinou", english: "yesterday", category: "time" },
    { japanese: "まいにち", romaji: "mainichi", english: "every day", category: "time" },
    { japanese: "まいあさ", romaji: "maiasa", english: "every morning", category: "time" },
    { japanese: "まいばん", romaji: "maiban", english: "every night", category: "time" },
    { japanese: "あさ", romaji: "asa", english: "morning", category: "time" },
    { japanese: "ひる", romaji: "hiru", english: "noon / daytime", category: "time" },
    { japanese: "ばん", romaji: "ban", english: "evening", category: "time" },
    { japanese: "よる", romaji: "yoru", english: "night", category: "time" },
    { japanese: "いま", romaji: "ima", english: "now", category: "time" },
    { japanese: "げつようび", romaji: "getsuyoubi", english: "Monday", category: "time" },
    { japanese: "かようび", romaji: "kayoubi", english: "Tuesday", category: "time" },
    { japanese: "すいようび", romaji: "suiyoubi", english: "Wednesday", category: "time" },
    { japanese: "もくようび", romaji: "mokuyoubi", english: "Thursday", category: "time" },
    { japanese: "きんようび", romaji: "kinyoubi", english: "Friday", category: "time" },
    { japanese: "どようび", romaji: "doyoubi", english: "Saturday", category: "time" },
    { japanese: "にちようび", romaji: "nichiyoubi", english: "Sunday", category: "time" },
    { japanese: "いち", romaji: "ichi", english: "one", category: "numbers" },
    { japanese: "に", romaji: "ni", english: "two", category: "numbers" },
    { japanese: "さん", romaji: "san", english: "three", category: "numbers" },
    { japanese: "よん", romaji: "yon", english: "four", category: "numbers" },
    { japanese: "ご", romaji: "go", english: "five", category: "numbers" },
    { japanese: "ろく", romaji: "roku", english: "six", category: "numbers" },
    { japanese: "なな", romaji: "nana", english: "seven", category: "numbers" },
    { japanese: "はち", romaji: "hachi", english: "eight", category: "numbers" },
    { japanese: "きゅう", romaji: "kyuu", english: "nine", category: "numbers" },
    { japanese: "じゅう", romaji: "juu", english: "ten", category: "numbers" },
    { japanese: "ひゃく", romaji: "hyaku", english: "hundred", category: "numbers" },
    { japanese: "せん", romaji: "sen", english: "thousand", category: "numbers" },
    { japanese: "おかね", romaji: "okane", english: "money", category: "daily life" },
    { japanese: "きっぷ", romaji: "kippu", english: "ticket", category: "daily life" },
    { japanese: "てがみ", romaji: "tegami", english: "letter", category: "daily life" },
    { japanese: "しゃしん", romaji: "shashin", english: "photo", category: "daily life" },
    { japanese: "かさ", romaji: "kasa", english: "umbrella", category: "daily life" },
    { japanese: "くつ", romaji: "kutsu", english: "shoes", category: "daily life" },
    { japanese: "うえ", romaji: "ue", english: "up / above", category: "position" },
    { japanese: "した", romaji: "shita", english: "down / below", category: "position" },
    { japanese: "まえ", romaji: "mae", english: "front / before", category: "position" },
    { japanese: "うしろ", romaji: "ushiro", english: "behind", category: "position" },
    { japanese: "なか", romaji: "naka", english: "inside", category: "position" },
    { japanese: "そと", romaji: "soto", english: "outside", category: "position" },
    { japanese: "ちかく", romaji: "chikaku", english: "nearby", category: "position" },
    { japanese: "となり", romaji: "tonari", english: "next to", category: "position" },
    { japanese: "ちち", romaji: "chichi", english: "my father", category: "family" },
    { japanese: "はは", romaji: "haha", english: "my mother", category: "family" },
    { japanese: "おとうさん", romaji: "otousan", english: "father / someone else's father", category: "family" },
    { japanese: "おかあさん", romaji: "okaasan", english: "mother / someone else's mother", category: "family" },
    { japanese: "あに", romaji: "ani", english: "my older brother", category: "family" },
    { japanese: "あね", romaji: "ane", english: "my older sister", category: "family" },
    { japanese: "おとうと", romaji: "otouto", english: "younger brother", category: "family" },
    { japanese: "いもうと", romaji: "imouto", english: "younger sister", category: "family" },
    { japanese: "つま", romaji: "tsuma", english: "my wife", category: "family" },
    { japanese: "おっと", romaji: "otto", english: "my husband", category: "family" },
    { japanese: "こども", romaji: "kodomo", english: "child", category: "family" },
    { japanese: "あめ", romaji: "ame", english: "rain", category: "weather" },
    { japanese: "ゆき", romaji: "yuki", english: "snow", category: "weather" },
    { japanese: "てんき", romaji: "tenki", english: "weather", category: "weather" },
    { japanese: "あたたかい", romaji: "atatakai", english: "warm", category: "weather" },
    { japanese: "すずしい", romaji: "suzushii", english: "cool / refreshing", category: "weather" },
    { japanese: "あまい", romaji: "amai", english: "sweet", category: "adjectives" },
    { japanese: "からい", romaji: "karai", english: "spicy", category: "adjectives" },
    { japanese: "おいしい", romaji: "oishii", english: "delicious", category: "adjectives" },
    { japanese: "まずい", romaji: "mazui", english: "bad tasting", category: "adjectives" },
    { japanese: "しずか", romaji: "shizuka", english: "quiet", category: "adjectives" },
    { japanese: "にぎやか", romaji: "nigiyaka", english: "lively", category: "adjectives" },
    { japanese: "べんり", romaji: "benri", english: "convenient", category: "adjectives" },
    { japanese: "げんき", romaji: "genki", english: "healthy / energetic", category: "adjectives" },
    { japanese: "わるい", romaji: "warui", english: "bad", category: "adjectives" },
    { japanese: "むずかしい", romaji: "muzukashii", english: "difficult", category: "adjectives" },
    { japanese: "やさしい", romaji: "yasashii", english: "easy / kind", category: "adjectives" },
    { japanese: "おもしろい", romaji: "omoshiroi", english: "interesting", category: "adjectives" },
    { japanese: "あう", romaji: "au", english: "to meet", category: "verbs" },
    { japanese: "あける", romaji: "akeru", english: "to open", category: "verbs" },
    { japanese: "しめる", romaji: "shimeru", english: "to close", category: "verbs" },
    { japanese: "まつ", romaji: "matsu", english: "to wait", category: "verbs" },
    { japanese: "つかう", romaji: "tsukau", english: "to use", category: "verbs" },
    { japanese: "わかる", romaji: "wakaru", english: "to understand", category: "verbs" },
    { japanese: "おぼえる", romaji: "oboeru", english: "to memorize", category: "verbs" },
    { japanese: "すむ", romaji: "sumu", english: "to live / reside", category: "verbs" },
    { japanese: "おきる", romaji: "okiru", english: "to wake up", category: "verbs" },
    { japanese: "ねる", romaji: "neru", english: "to sleep", category: "verbs" },
    { japanese: "いくら", romaji: "ikura", english: "how much", category: "questions" },
    { japanese: "どこ", romaji: "doko", english: "where", category: "questions" },
    { japanese: "だれ", romaji: "dare", english: "who", category: "questions" },
    { japanese: "なに", romaji: "nani", english: "what", category: "questions" },
    { japanese: "いつ", romaji: "itsu", english: "when", category: "questions" },
    { japanese: "どう", romaji: "dou", english: "how", category: "questions" },
    { japanese: "どうして", romaji: "doushite", english: "why", category: "questions" },
    { japanese: "どれ", romaji: "dore", english: "which one", category: "questions" },
    { japanese: "まち", romaji: "machi", english: "town / city", category: "places" },
    { japanese: "くに", romaji: "kuni", english: "country", category: "places" },
    { japanese: "にほん", romaji: "nihon", english: "Japan", category: "places" },
    { japanese: "アメリカ", romaji: "amerika", english: "America", category: "places" },
    { japanese: "へや", romaji: "heya", english: "room", category: "places" },
    { japanese: "アパート", romaji: "apaato", english: "apartment", category: "places" },
    { japanese: "こうえん", romaji: "kouen", english: "park", category: "places" },
    { japanese: "レストラン", romaji: "resutoran", english: "restaurant", category: "places" },
    { japanese: "スーパー", romaji: "suupaa", english: "supermarket", category: "places" },
    { japanese: "コンビニ", romaji: "konbini", english: "convenience store", category: "places" },
    { japanese: "にほんご", romaji: "nihongo", english: "Japanese language", category: "study" },
    { japanese: "えいご", romaji: "eigo", english: "English language", category: "study" },
    { japanese: "べんきょう", romaji: "benkyou", english: "study", category: "study" },
    { japanese: "しゅくだい", romaji: "shukudai", english: "homework", category: "study" },
    { japanese: "なまえ", romaji: "namae", english: "name", category: "people" },
    { japanese: "しごと", romaji: "shigoto", english: "work / job", category: "daily life" },
    { japanese: "やすみ", romaji: "yasumi", english: "rest / day off", category: "daily life" },
    { japanese: "じかん", romaji: "jikan", english: "time", category: "time" },
    { japanese: "はん", romaji: "han", english: "half past", category: "time" },
    { japanese: "はやい", romaji: "hayai", english: "early / fast", category: "adjectives" },
    { japanese: "おそい", romaji: "osoi", english: "late / slow", category: "adjectives" },
    { japanese: "たのしい", romaji: "tanoshii", english: "fun", category: "adjectives" },
    { japanese: "つかれる", romaji: "tsukareru", english: "to get tired", category: "verbs" },
    { japanese: "べんきょうする", romaji: "benkyou suru", english: "to study", category: "verbs" },
    { japanese: "れんしゅうする", romaji: "renshuu suru", english: "to practice", category: "verbs" },
    { japanese: "はたらく", romaji: "hataraku", english: "to work", category: "verbs" },
    { japanese: "あそぶ", romaji: "asobu", english: "to play / hang out", category: "verbs" },
    { japanese: "はい", romaji: "hai", english: "yes", category: "conversation" },
    { japanese: "いいえ", romaji: "iie", english: "no", category: "conversation" },
    { japanese: "だいじょうぶ", romaji: "daijoubu", english: "okay / all right", category: "conversation" },
    { japanese: "ちょっと", romaji: "chotto", english: "a little / one moment", category: "conversation" },
    { japanese: "アメリカじん", romaji: "amerikajin", english: "American person", category: "people" },
    { japanese: "つくえ", romaji: "tsukue", english: "desk", category: "daily life" },
    { japanese: "いす", romaji: "isu", english: "chair", category: "daily life" },
    { japanese: "きょうしつ", romaji: "kyoushitsu", english: "classroom", category: "places" },
    { japanese: "みち", romaji: "michi", english: "road / street", category: "places" },
    { japanese: "みぎ", romaji: "migi", english: "right", category: "directions" },
    { japanese: "ひだり", romaji: "hidari", english: "left", category: "directions" },
    { japanese: "まっすぐ", romaji: "massugu", english: "straight ahead", category: "directions" },
    { japanese: "すこし", romaji: "sukoshi", english: "a little", category: "conversation" },
    { japanese: "ゆっくり", romaji: "yukkuri", english: "slowly", category: "conversation" },
    { japanese: "なん", romaji: "nan", english: "what", category: "questions" },
    { japanese: "ここ", romaji: "koko", english: "here", category: "position" },
    { japanese: "そこ", romaji: "soko", english: "there", category: "position" },
    { japanese: "あそこ", romaji: "asoko", english: "over there", category: "position" },
    { japanese: "たすける", romaji: "tasukeru", english: "to help / save", category: "verbs" },
    { japanese: "ひつよう", romaji: "hitsuyou", english: "necessary / needed", category: "adjectives" },
    { japanese: "いりません", romaji: "irimasen", english: "I do not need it", category: "conversation" }
  ],
  particles: [
    { particle: "は", romaji: "wa", role: "topic marker", example: "わたしはアメリカじんです。", english: "I am American." },
    { particle: "が", romaji: "ga", role: "subject marker", example: "みずがあります。", english: "There is water." },
    { particle: "を", romaji: "o", role: "object marker", example: "ごはんをたべます。", english: "I eat a meal." },
    { particle: "に", romaji: "ni", role: "time / destination", example: "えきにいきます。", english: "I go to the station." },
    { particle: "で", romaji: "de", role: "place of action", example: "いえでたべます。", english: "I eat at home." },
    { particle: "の", romaji: "no", role: "possession / description", example: "わたしのいえです。", english: "It is my house." },
    { particle: "も", romaji: "mo", role: "also / too", example: "わたしもいきます。", english: "I will go too." },
    { particle: "と", romaji: "to", role: "and / with", example: "ともだちといきます。", english: "I go with a friend." },
    { particle: "へ", romaji: "e", role: "direction toward", example: "にほんへいきます。", english: "I go to Japan." },
    { particle: "から", romaji: "kara", role: "from / because", example: "くじからです。", english: "It is from nine." },
    { particle: "まで", romaji: "made", role: "until / to", example: "ごじまでです。", english: "It is until five." },
    { particle: "か", romaji: "ka", role: "question marker", example: "これはみずですか。", english: "Is this water?" }
  ],
  particlePractice: [
    { prompt: "わたし ___ がくせいです。", answer: "は", choices: ["は", "を", "で", "の"], explanation: "は marks the topic: as for me, I am a student." },
    { prompt: "みず ___ ください。", answer: "を", choices: ["を", "に", "が", "と"], explanation: "を marks the thing requested or acted on." },
    { prompt: "えき ___ いきます。", answer: "に", choices: ["に", "で", "も", "の"], explanation: "に marks the destination here." },
    { prompt: "いえ ___ たべます。", answer: "で", choices: ["で", "は", "を", "へ"], explanation: "で marks where an action happens." },
    { prompt: "わたし ___ いえです。", answer: "の", choices: ["の", "が", "と", "に"], explanation: "の shows possession: my house." },
    { prompt: "ともだち ___ いきます。", answer: "と", choices: ["と", "を", "で", "は"], explanation: "と can mean with when naming a person you do something with." },
    { prompt: "わたし ___ いきます。", answer: "も", choices: ["も", "の", "を", "で"], explanation: "も means also or too." },
    { prompt: "にほん ___ いきます。", answer: "へ", choices: ["へ", "を", "が", "も"], explanation: "へ marks direction toward a place." },
    { prompt: "ほん ___ よみます。", answer: "を", choices: ["を", "で", "に", "は"], explanation: "を marks the direct object: the book is what you read." },
    { prompt: "がっこう ___ べんきょうします。", answer: "で", choices: ["で", "を", "の", "と"], explanation: "で marks where the study action happens." },
    { prompt: "あした ___ いきます。", answer: "も", choices: ["も", "へ", "の", "を"], explanation: "も adds also/too: tomorrow too." },
    { prompt: "つくえ ___ うえにほんがあります。", answer: "の", choices: ["の", "を", "と", "が"], explanation: "の connects nouns: on top of the desk." },
    { prompt: "あさしちじ ___ おきます。", answer: "に", choices: ["に", "で", "を", "が"], explanation: "に marks a specific time." },
    { prompt: "あめ ___ ふっています。", answer: "が", choices: ["が", "を", "に", "と"], explanation: "が marks the subject in this weather sentence." },
    { prompt: "くじ ___ ごじまでべんきょうします。", answer: "から", choices: ["から", "まで", "を", "の"], explanation: "から marks the starting point: from nine." },
    { prompt: "くじからごじ ___ べんきょうします。", answer: "まで", choices: ["まで", "から", "に", "が"], explanation: "まで marks the end point: until five." },
    { prompt: "これはみずです ___ 。", answer: "か", choices: ["か", "を", "で", "と"], explanation: "か turns the sentence into a question." },
    { prompt: "にほんご ___ べんきょうします。", answer: "を", choices: ["を", "が", "に", "から"], explanation: "を marks にほんご as what you study." },
    { prompt: "コンビニ ___ パンをかいます。", answer: "で", choices: ["で", "へ", "の", "か"], explanation: "で marks where the buying happens." },
    { prompt: "アメリカ ___ きました。", answer: "から", choices: ["から", "まで", "を", "で"], explanation: "から marks the place someone came from." },
    { prompt: "レストラン ___ ともだちがいます。", answer: "に", choices: ["に", "を", "か", "も"], explanation: "に marks the location where someone exists." },
    { prompt: "これはわたし ___ かばんです。", answer: "の", choices: ["の", "で", "から", "か"], explanation: "の connects possession: my bag." },
    { prompt: "きょうしつ ___ べんきょうします。", answer: "で", choices: ["で", "に", "が", "か"], explanation: "で marks the place where an action happens." },
    { prompt: "きょうしつ ___ せんせいがいます。", answer: "に", choices: ["に", "で", "を", "まで"], explanation: "に marks where a person exists." },
    { prompt: "わたし ___ アメリカじんです。", answer: "は", choices: ["は", "が", "を", "で"], explanation: "は marks the topic: as for me, I am American." },
    { prompt: "だれ ___ きましたか。", answer: "が", choices: ["が", "を", "で", "まで"], explanation: "が marks the subject in many who/what questions." },
    { prompt: "えき ___ みぎです。", answer: "は", choices: ["は", "を", "で", "から"], explanation: "は marks the topic: the station is to the right." }
  ],
  grammarPatterns: [
    { pattern: "A は B です", romaji: "A wa B desu", meaning: "A is B.", example: "わたしはがくせいです。" },
    { pattern: "A は B じゃないです", romaji: "A wa B janai desu", meaning: "A is not B.", example: "これはみずじゃないです。" },
    { pattern: "A に いきます", romaji: "A ni ikimasu", meaning: "I go to A.", example: "えきにいきます。" },
    { pattern: "A を ください", romaji: "A o kudasai", meaning: "Please give me A.", example: "みずをください。" },
    { pattern: "A は どこですか", romaji: "A wa doko desu ka", meaning: "Where is A?", example: "えきはどこですか。" },
    { pattern: "A が あります", romaji: "A ga arimasu", meaning: "There is A / I have A (non-living things).", example: "みずがあります。" },
    { pattern: "A が います", romaji: "A ga imasu", meaning: "There is A / I have A (living things).", example: "ともだちがいます。" },
    { pattern: "A を ます-form", romaji: "A o masu-form", meaning: "Do an action to A.", example: "ほんをよみます。" },
    { pattern: "A と B", romaji: "A to B", meaning: "A and B / with B.", example: "ともだちといきます。" },
    { pattern: "A は B ですか", romaji: "A wa B desu ka", meaning: "Is A B?", example: "これはみずですか。" },
    { pattern: "A じゃありません", romaji: "A ja arimasen", meaning: "It is not A.", example: "これはほんじゃありません。" },
    { pattern: "ます / ません", romaji: "masu / masen", meaning: "Polite present affirmative / negative.", example: "いきます。いきません。" },
    { pattern: "ました / ませんでした", romaji: "mashita / masen deshita", meaning: "Polite past affirmative / negative.", example: "いきました。いきませんでした。" },
    { pattern: "A から B まで", romaji: "A kara B made", meaning: "from A to B.", example: "くじからごじまでです。" },
    { pattern: "A の うえ / した", romaji: "A no ue / shita", meaning: "above / below A.", example: "つくえのうえにあります。" },
    { pattern: "i-adjective + です", romaji: "i-adjective desu", meaning: "Polite adjective sentence.", example: "このほんはおもしろいです。" },
    { pattern: "na-adjective + です", romaji: "na-adjective desu", meaning: "Polite na-adjective sentence.", example: "このまちはしずかです。" },
    { pattern: "A は B でした", romaji: "A wa B deshita", meaning: "A was B.", example: "きのうはやすみでした。" },
    { pattern: "A は B じゃありませんでした", romaji: "A wa B ja arimasen deshita", meaning: "A was not B.", example: "きのうはひまじゃありませんでした。" },
    { pattern: "A が すきです", romaji: "A ga suki desu", meaning: "I like A.", example: "にほんごがすきです。" },
    { pattern: "A が ほしいです", romaji: "A ga hoshii desu", meaning: "I want A.", example: "みずがほしいです。" },
    { pattern: "A たいです", romaji: "A tai desu", meaning: "I want to do A.", example: "にほんへいきたいです。" },
    { pattern: "A ましょう", romaji: "A mashou", meaning: "Let's do A.", example: "べんきょうしましょう。" }
  ],
  grammarPractice: [
    { prompt: "Which pattern means 'A is B'?", answer: "A は B です", choices: ["A は B です", "A を ください", "A が います", "A に いきます"], explanation: "A は B です is the basic identity sentence." },
    { prompt: "Which sentence means 'Where is the station?'", answer: "えきはどこですか。", choices: ["えきはどこですか。", "えきにいきます。", "えきでたべます。", "えきがあります。"], explanation: "A は どこですか asks where A is." },
    { prompt: "Which pattern asks for something?", answer: "A を ください", choices: ["A を ください", "A は B です", "A が います", "A に いきます"], explanation: "A を ください means please give me A." },
    { prompt: "Use あります for...", answer: "non-living things", choices: ["non-living things", "people and animals", "only questions", "only food"], explanation: "あります is used for non-living things; います is for living things." },
    { prompt: "Use います for...", answer: "people and animals", choices: ["people and animals", "places", "prices", "books only"], explanation: "います is used for living things." },
    { prompt: "Which sentence means 'I go to the station?'", answer: "えきにいきます。", choices: ["えきにいきます。", "えきをください。", "えきはみずです。", "えきでよみます。"], explanation: "A に いきます marks the destination." },
    { prompt: "Which sentence means 'I like Japanese?'", answer: "にほんごがすきです。", choices: ["にほんごがすきです。", "にほんごをください。", "にほんごへいきます。", "にほんごはどこですか。"], explanation: "A が すきです says that you like A." },
    { prompt: "Which pattern means 'I want A?'", answer: "A が ほしいです", choices: ["A が ほしいです", "A は B でした", "A に いきます", "A と B"], explanation: "A が ほしいです is the beginner pattern for wanting a thing." },
    { prompt: "Which sentence means 'I want to go to Japan?'", answer: "にほんへいきたいです。", choices: ["にほんへいきたいです。", "にほんへいきました。", "にほんへいきません。", "にほんへいきましょう。"], explanation: "たいです attaches to a verb stem to say want to do." },
    { prompt: "Which sentence is past tense?", answer: "きのう、べんきょうしました。", choices: ["きのう、べんきょうしました。", "きょう、べんきょうします。", "あした、べんきょうします。", "まいにち、べんきょうします。"], explanation: "ました is polite past tense." },
    { prompt: "Which pattern suggests doing something together?", answer: "A ましょう", choices: ["A ましょう", "A が ほしいです", "A じゃありません", "A は B でした"], explanation: "ましょう is used for let's do A." },
    { prompt: "Which sentence means 'Yesterday was a day off?'", answer: "きのうはやすみでした。", choices: ["きのうはやすみでした。", "きのうはやすみです。", "あしたはやすみです。", "やすみをください。"], explanation: "でした makes the sentence past tense." },
    { prompt: "Which sentence means 'This is not water?'", answer: "これはみずじゃないです。", choices: ["これはみずじゃないです。", "これはみずですか。", "みずをください。", "みずがほしいです。"], explanation: "じゃないです is a beginner-friendly negative form." },
    { prompt: "Which sentence means 'I do not go?'", answer: "いきません。", choices: ["いきません。", "いきます。", "いきました。", "いきたいです。"], explanation: "ません is the polite negative present form." },
    { prompt: "Which sentence means 'I did not study?'", answer: "べんきょうしませんでした。", choices: ["べんきょうしませんでした。", "べんきょうしました。", "べんきょうします。", "べんきょうしましょう。"], explanation: "ませんでした is the polite negative past form." },
    { prompt: "Which sentence means 'Is this a desk?'", answer: "これはつくえですか。", choices: ["これはつくえですか。", "これはつくえです。", "つくえはどこですか。", "つくえをください。"], explanation: "か marks a question." },
    { prompt: "Which sentence means 'The room is not quiet?'", answer: "へやはしずかじゃないです。", choices: ["へやはしずかじゃないです。", "へやはしずかです。", "へやはどこですか。", "へやにいます。"], explanation: "じゃないです negates a na-adjective sentence." }
  ],
  sentencePractice: [
    { prompt: "わたしはアメリカじんです。", answer: "I am American.", choices: ["I am American.", "I go to America.", "America is here.", "I want water."], explanation: "は marks the topic and です makes the sentence polite." },
    { prompt: "えきはどこですか。", answer: "Where is the station?", choices: ["Where is the station?", "Is this a station?", "I go to the station.", "The station is big."], explanation: "どこですか asks where something is." },
    { prompt: "みずをください。", answer: "Water, please.", choices: ["Water, please.", "There is water.", "I drink water.", "Water is expensive."], explanation: "A を ください is a useful request pattern." },
    { prompt: "ほんをよみます。", answer: "I read a book.", choices: ["I read a book.", "I buy a book.", "The book is new.", "There is a book."], explanation: "を marks ほん as the object of よみます." },
    { prompt: "あした、がっこうにいきます。", answer: "Tomorrow, I will go to school.", choices: ["Tomorrow, I will go to school.", "Yesterday, I went home.", "Every morning, I sleep.", "Today, I buy a ticket."], explanation: "に marks the destination, and あした sets the time." },
    { prompt: "つくえのうえにかばんがあります。", answer: "There is a bag on the desk.", choices: ["There is a bag on the desk.", "The bag is under the desk.", "I bought a desk.", "The desk is quiet."], explanation: "のうえに means on top of, and あります is for non-living things." },
    { prompt: "ともだちとバスでいきます。", answer: "I go by bus with a friend.", choices: ["I go by bus with a friend.", "My friend drives a car.", "The bus is old.", "I wait for a friend."], explanation: "と marks with, and で can mark the means of transportation." },
    { prompt: "このまちはしずかです。", answer: "This town is quiet.", choices: ["This town is quiet.", "This town is lively.", "This shop is cheap.", "This train is fast."], explanation: "しずか is a na-adjective used with です here." },
    { prompt: "あさしちじにおきます。", answer: "I wake up at seven in the morning.", choices: ["I wake up at seven in the morning.", "I sleep at seven at night.", "I leave at noon.", "I study every night."], explanation: "に marks the specific time when the action happens." },
    { prompt: "すみません、もういちどおねがいします。", answer: "Excuse me, one more time please.", choices: ["Excuse me, one more time please.", "Thank you very much.", "Where is the restroom?", "Please speak quickly."], explanation: "This is a survival phrase for listening practice." },
    { prompt: "にほんごがすきです。", answer: "I like Japanese.", choices: ["I like Japanese.", "I speak English.", "I want water.", "I am from Japan."], explanation: "A が すきです says you like A." },
    { prompt: "みずがほしいです。", answer: "I want water.", choices: ["I want water.", "Water is cheap.", "There is water.", "Please drink water."], explanation: "A が ほしいです says you want a thing." },
    { prompt: "にほんへいきたいです。", answer: "I want to go to Japan.", choices: ["I want to go to Japan.", "I came from Japan.", "Japan is quiet.", "I study Japanese."], explanation: "いきたいです means want to go." },
    { prompt: "きのう、べんきょうしました。", answer: "Yesterday, I studied.", choices: ["Yesterday, I studied.", "Tomorrow, I will study.", "Every day, I study.", "I do not understand."], explanation: "ました marks polite past tense." },
    { prompt: "あした、レストランでともだちとあいます。", answer: "Tomorrow, I will meet a friend at a restaurant.", choices: ["Tomorrow, I will meet a friend at a restaurant.", "Yesterday, I worked at a restaurant.", "I want a restaurant ticket.", "My friend is at the station."], explanation: "で marks where the meeting happens, and と marks with whom." },
    { prompt: "くじからごじまでしごとです。", answer: "Work is from nine to five.", choices: ["Work is from nine to five.", "I work at five only.", "I go to work by train.", "Nine tickets, please."], explanation: "から and まで mark from and until." },
    { prompt: "コンビニでパンとコーヒーをかいます。", answer: "I buy bread and coffee at the convenience store.", choices: ["I buy bread and coffee at the convenience store.", "The convenience store is near the station.", "I drink coffee at home.", "Bread is expensive."], explanation: "で marks the place of action, と links nouns, and を marks what is bought." },
    { prompt: "すみません、えいごをはなせますか。", answer: "Excuse me, can you speak English?", choices: ["Excuse me, can you speak English?", "Excuse me, where is English?", "Please speak Japanese slowly.", "I do not understand English."], explanation: "はなせますか asks if someone can speak." },
    { prompt: "だいじょうぶです。", answer: "It is okay.", choices: ["It is okay.", "It is expensive.", "It is near.", "It is my name."], explanation: "だいじょうぶです is a useful reassurance phrase." },
    { prompt: "これはなんですか。", answer: "What is this?", choices: ["What is this?", "Where is this?", "How much is this?", "Is this okay?"], explanation: "なんですか asks what something is." },
    { prompt: "ここはどこですか。", answer: "Where is here?", choices: ["Where is here?", "Who is here?", "Is this water?", "Please wait here."], explanation: "ここ means here, and どこ asks where." },
    { prompt: "えきはみぎです。", answer: "The station is to the right.", choices: ["The station is to the right.", "The station is to the left.", "The station is straight ahead.", "The station is expensive."], explanation: "みぎ means right." },
    { prompt: "コンビニはまっすぐです。", answer: "The convenience store is straight ahead.", choices: ["The convenience store is straight ahead.", "The convenience store is behind me.", "The convenience store is closed.", "The convenience store is cheap."], explanation: "まっすぐ is a useful direction word." },
    { prompt: "もうすこしゆっくりおねがいします。", answer: "A little more slowly, please.", choices: ["A little more slowly, please.", "One more ticket, please.", "Please wait here.", "Please help me."], explanation: "This is a practical listening-survival phrase." },
    { prompt: "たすけてください。", answer: "Please help me.", choices: ["Please help me.", "Please speak slowly.", "Please wait.", "Please give me water."], explanation: "たすけてください is an emergency help phrase." },
    { prompt: "いりません。", answer: "I do not need it.", choices: ["I do not need it.", "I do not understand.", "I want to go.", "I am okay."], explanation: "いりません is useful for declining something." },
    { prompt: "だいじょうぶですか。", answer: "Are you okay?", choices: ["Are you okay?", "Is it expensive?", "Where is it?", "Do you speak English?"], explanation: "Adding か makes だいじょうぶです a question." }
  ],
  starterPhrases: [
    { japanese: "おはようございます。", romaji: "Ohayo gozaimasu.", english: "Good morning.", note: "Polite and safe." },
    { japanese: "こんにちは。", romaji: "Konnichiwa.", english: "Hello / good afternoon.", note: "Basic greeting." },
    { japanese: "ありがとうございます。", romaji: "Arigato gozaimasu.", english: "Thank you.", note: "Polite thank you." },
    { japanese: "すみません。", romaji: "Sumimasen.", english: "Excuse me / sorry.", note: "One of the most useful words." },
    { japanese: "おねがいします。", romaji: "Onegai shimasu.", english: "Please.", note: "Useful in requests." },
    { japanese: "わかりません。", romaji: "Wakarimasen.", english: "I do not understand.", note: "Beginner survival phrase." },
    { japanese: "もういちどおねがいします。", romaji: "Mo ichido onegai shimasu.", english: "One more time, please.", note: "Use when listening is too fast." },
    { japanese: "ゆっくりおねがいします。", romaji: "Yukkuri onegai shimasu.", english: "Slowly, please.", note: "Shorter beginner version." },
    { japanese: "トイレはどこですか。", romaji: "Toire wa doko desu ka.", english: "Where is the restroom?", note: "High-value travel phrase." },
    { japanese: "これはいくらですか。", romaji: "Kore wa ikura desu ka.", english: "How much is this?", note: "Shopping and daily life." },
    { japanese: "えきにいきます。", romaji: "Eki ni ikimasu.", english: "I am going to the station.", note: "Uses the destination particle に." },
    { japanese: "みずをください。", romaji: "Mizu o kudasai.", english: "Water, please.", note: "Simple request pattern." },
    { japanese: "にほんごをべんきょうしています。", romaji: "Nihongo o benkyou shite imasu.", english: "I am studying Japanese.", note: "Useful self-introduction detail." },
    { japanese: "すこしにほんごがわかります。", romaji: "Sukoshi nihongo ga wakarimasu.", english: "I understand a little Japanese.", note: "Honest beginner phrase." },
    { japanese: "えいごをはなせますか。", romaji: "Eigo o hanasemasu ka.", english: "Can you speak English?", note: "Useful support phrase." },
    { japanese: "もういちどいってください。", romaji: "Mo ichido itte kudasai.", english: "Please say it one more time.", note: "Slightly fuller version of the survival phrase." },
    { japanese: "だいじょうぶです。", romaji: "Daijobu desu.", english: "It is okay.", note: "Useful for reassurance or declining help softly." },
    { japanese: "ちょっとまってください。", romaji: "Chotto matte kudasai.", english: "Please wait a moment.", note: "Useful when you need time." },
    { japanese: "にほんごがすきです。", romaji: "Nihongo ga suki desu.", english: "I like Japanese.", note: "Simple positive self-introduction phrase." },
    { japanese: "にほんへいきたいです。", romaji: "Nihon e ikitai desu.", english: "I want to go to Japan.", note: "Uses the want-to-do pattern." },
    { japanese: "アメリカからきました。", romaji: "Amerika kara kimashita.", english: "I came from America.", note: "Useful introduction phrase." },
    { japanese: "くじからごじまでです。", romaji: "Kuji kara goji made desu.", english: "It is from nine to five.", note: "Practice from/until timing." },
    { japanese: "もうすこしゆっくりおねがいします。", romaji: "Mo sukoshi yukkuri onegai shimasu.", english: "A little more slowly, please.", note: "Useful when normal speech is too fast." },
    { japanese: "これはなんですか。", romaji: "Kore wa nan desu ka.", english: "What is this?", note: "Useful for asking about unfamiliar things." },
    { japanese: "ここはどこですか。", romaji: "Koko wa doko desu ka.", english: "Where is here?", note: "Useful if you are disoriented." },
    { japanese: "たすけてください。", romaji: "Tasukete kudasai.", english: "Please help me.", note: "Emergency phrase." },
    { japanese: "いりません。", romaji: "Irimasen.", english: "I do not need it.", note: "Useful for declining offers or bags." },
    { japanese: "だいじょうぶですか。", romaji: "Daijobu desu ka.", english: "Are you okay?", note: "Simple check-in phrase." }
  ],
  nameTransliterations: [
    {
      input: ["sean", "shawn", "shaun"],
      katakana: "ショーン",
      hiragana: "しょーん",
      sound: "shon / shoon",
      note: "English names are written by sound in katakana, so Sean follows the Shawn sound rather than the letters s-e-a-n."
    },
    {
      input: ["michael", "mike"],
      katakana: "マイケル",
      hiragana: "まいける",
      sound: "maikeru",
      note: "A common katakana form for Michael. Mike is often adapted from the same sound family."
    },
    {
      input: ["sarah", "sara"],
      katakana: "サラ",
      hiragana: "さら",
      sound: "sara",
      note: "A common katakana form for Sarah/Sara."
    },
    {
      input: ["emily", "emilie"],
      katakana: "エミリー",
      hiragana: "えみりー",
      sound: "emirii",
      note: "Emily is commonly adapted as エミリー, with the long vowel mark at the end."
    },
    {
      input: ["mark", "marc"],
      katakana: "マーク",
      hiragana: "まーく",
      sound: "maaku",
      note: "Mark/Marc is commonly adapted as マーク, with the long vowel mark after マ."
    },
    {
      input: ["john", "jon"],
      katakana: "ジョン",
      hiragana: "じょん",
      sound: "jon",
      note: "John is written from the sound, not the letters."
    },
    {
      input: ["conor", "connor"],
      katakana: "コナー",
      hiragana: "こなー",
      sound: "konaa",
      note: "Conor/Connor is commonly adapted by sound as コナー, with the long vowel mark extending the final sound."
    },
    {
      input: ["david", "dave"],
      katakana: "デイビッド",
      hiragana: "でいびっど",
      sound: "deibiddo",
      note: "David often becomes デイビッド in Japanese."
    }
  ],
  kanjiLater: {
    title: "Kanji Later, Not Day One",
    message: "Kanji will become a side quest after kana feels familiar. First target: confidence with hiragana, katakana, particles, and simple N5 sentences."
  }
};
